spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: none
flyway:
    enabled: true
---
spring:
    profiles: localhost_external
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
flyway:
    enabled: false