CREATE TABLE MEMBER (`id` INT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(255));

INSERT INTO MEMBER (`name`) VALUES ('Bruce');
INSERT INTO MEMBER (`name`) VALUES ('A-Ming');
INSERT INTO MEMBER (`name`) VALUES ('Steve');
INSERT INTO MEMBER (`name`) VALUES ('Bill');